### ISSUE TITLE
Suggestion: `set` = `register`

### ISSUE THREAD

**Issue by alanning** [xolvio/inverter#1]
Nice package!  This solves a very common issue.  Usually I would hang functions off my own application object but its nice to have a standard like this.

One suggestion would be to have `set` be an alias of `register`.  That would fit well with the existing `Session` get/set syntax.

May also want to show an example of how you could use your own main app object to store the container.  For example,

```
S911.container = Inverter;

var clickButtonEvent = S911.container.get(...);
```

**Comment by SamHatoum** [comment]
good thinking.

I also need to make this work on the server. no need why it shouldn't

**Comment by SamHatoum** [comment]
Ask and you shall receive :)

**Comment by queso** [comment]
Nice, I like the container syntax

**Comment by SamHatoum** [comment]
I get it, I get it

https://github.com/xolvio/inverter#use-your-namespace

I also added multiple container support whilst in there :)
