### ISSUE TITLE
Modifying String prototype?

### ISSUE THREAD

**Issue by awei01** [xolvio/inverter#3]
Hi,

Great package. One thing that I'm not sold on is adding the hashCode() method on the String prototype. It feels like this kind of breaks the encapsulation of the package as it has some side effects that consumers may not be aware of. Granted, there is very little chance of this really being a factor, but it seems like it's contrary to the `spirit` of packages. Anyway, just my 2 cents. Feel free to disabuse me of my opinion.

**Comment by SamHatoum** [comment]
I guess we could add some docs to the main page letting users know. I also feel hashCode is a missing method from strings that's available in other languages on strings. Ho hum :)

**Comment by awei01** [comment]
Ok, thanks for the explanation. Makes sense.
